--- #YAML:1.0
name:               SweetPea
version:            2.366
abstract:           A web framework that doesn't get in the way, or suck.
author:
    - Al Newkirk <al.newkirk@awnstudio.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:           0
    CGI::Cookie:   0
    CGI::Session:  0
    perl:          5.006
    Test::More:    0
resources:
    repository:  http://github.com/awnstudio/SweetPea
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
