--- #YAML:1.0
name:               SweetPea
version:            2.00
abstract:           A simple light-weight web application framework based on an MVC design pattern using only CGI!
author:
    - Al Newkirk <al.newkirk@awnstudio.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:         1
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
